# Generated by Django 4.0 on 2022-04-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='work_status',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
