# Generated by Django 4.0.4 on 2022-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userpersonaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.AddField(
            model_name='userprofiledetails',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
