# Generated by Django 4.0.4 on 2022-04-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_resume_userprofiledetails_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='work_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
