# Generated by Django 4.0.4 on 2022-04-28 04:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userpersonaldetails_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetails',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profilepics/'),
        ),
    ]
