# Generated by Django 4.0.4 on 2022-04-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userprofiledetails_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetails',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='user_profilepics/'),
        ),
        migrations.AlterField(
            model_name='userprofiledetails',
            name='resume',
            field=models.FileField(null=True, upload_to='user_resume/'),
        ),
    ]
