# Generated by Django 4.0.4 on 2022-04-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userprofiledetails_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetails',
            name='resume',
            field=models.ImageField(null=True, upload_to='user_resume/'),
        ),
    ]
