# Generated by Django 4.0.4 on 2022-04-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_savedjobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedJobs',
        ),
    ]
