# Generated by Django 4.0.4 on 2022-04-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_savedjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_hr',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
