# Generated by Django 4.0.4 on 2022-05-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_customuser_is_hr_remove_customuser_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='skills',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
