# Generated by Django 4.0.4 on 2022-06-02 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_userskills_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_begin', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
