# Generated by Django 4.0.4 on 2022-06-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_premiumcustomers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumCustomers',
        ),
    ]
