# Generated by Django 4.0.4 on 2022-04-26 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_module', '0002_delete_hr_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_recruiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('about_company', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('experience_required', models.CharField(max_length=500)),
                ('job_description', models.TextField()),
                ('job_highlights', models.CharField(max_length=500)),
                ('educational_requirments', models.CharField(max_length=500)),
                ('salary_from', models.IntegerField()),
                ('salary_to', models.IntegerField()),
                ('requirements', models.TextField()),
                ('hr_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting', to='hr_module.hr_recruiter')),
            ],
        ),
    ]
