# Generated by Django 4.0.4 on 2022-04-28 06:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_module', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hr_Recruiter',
            new_name='HrRecruiter',
        ),
        migrations.RenameModel(
            old_name='Post_Job',
            new_name='PostJob',
        ),
    ]
