# Generated by Django 4.0.4 on 2022-05-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0004_rename_hr_recruiter_hrrecruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='posting_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
