# Generated by Django 4.0.4 on 2022-05-13 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_module', '0005_alter_postjob_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='hr_recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HrRecruiter',
        ),
    ]
