# Generated by Django 4.0.4 on 2022-05-26 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_module', '0008_postjob_skills_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
                ('plan_name', models.CharField(max_length=200, unique=True)),
                ('duration', models.CharField(max_length=200)),
                ('plan_rate', models.CharField(max_length=100)),
                ('plan_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AppliedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True, null=True)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='hr_module.postjob')),
                ('applied_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
