# Generated by Django 4.0.4 on 2022-05-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0011_alter_premiumplans_plan_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumplans',
            name='duration',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
